#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CustomRowView.Resource", IsApplication=true)]

namespace CustomRowView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cellback = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bulbs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CustomSelector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ESCUDO_UP = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int FlowerBuds = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Fruits = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_stat_av_play_over_video = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_stat_av_stop_over_video = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Legumes = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int MediosUP = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int splash = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Tubers = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Vegetables = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int Image = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int List = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int Text = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Text1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Text2 = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int footer = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int imageView1 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int playButton = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int stopButton = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HomeScreen = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
